name: Docker Compose Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (optional, required for private images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and run services using docker-compose
      - name: Run Docker Compose
        run: |
          docker-compose up --build -d

      # Step 5: Run tests (optional)
      - name: Run Tests
        run: |
          docker-compose exec <service_name> <test_command>

      # Step 6: Shut down services
      - name: Tear Down
        if: always()
        run: |
          docker-compose down
