name: Docker Compose Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to Docker Hub (optional, required for private images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and run services using docker-compose
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
              sudo apt update
              sudo apt install -y docker-compose docker.io
              sudo systemctl start docker
              sudo systemctl enable docker

              # Set up SSH for GitHub on the remote machine
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/git
              chmod 600 ~/.ssh/git

              # Add GitHub's SSH host key to known_hosts to prevent host verification issues
              ssh-keyscan github.com >> ~/.ssh/known_hosts

              # Clone or update the repository
              if [ ! -d "portfolio_web/.git" ]; then
                git clone git@github.com:oiskenderov/portfolio_web.git
              else
                cd portfolio_web
                git pull origin main
              fi

              # Build and run the services
              cd portfolio_web
              docker-compose up --build .

            
