name: Docker Compose Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install docker-compose
      #- name: Install Docker Compose
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y docker-compose

      # Step 4: Log in to Docker Hub (optional, required for private images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and run services using docker-compose
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            script: |
              sudo systemctl start docker
              sudo systemctl enable docker
              git pull
              docker-compose down
              docker-compose up --build -d
        
